server:
  port: 7001
#注册中心
eureka:
  instance:
    hostname: localhost  #Eureka服务端的实例名称
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    fetch-registry: false  #表示自己就是注册中心，不需要去检索服务
    register-with-eureka: true #表示自己就是注册中心，不再需要自己注册自己
